2025-04-13 05:41:40,583 INFO    MainThread:2940751 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /home/guswls/EEN4015_Intro2ML/pbl-2/wandb/run-20250413_054140-65vh8sp4/logs/debug.log
2025-04-13 05:41:40,583 INFO    MainThread:2940751 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /home/guswls/EEN4015_Intro2ML/pbl-2/wandb/run-20250413_054140-65vh8sp4/logs/debug-internal.log
2025-04-13 05:41:40,584 INFO    MainThread:2940751 [wandb_init.py:init():781] calling init triggers
2025-04-13 05:41:40,584 INFO    MainThread:2940751 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-04-13 05:41:40,584 INFO    MainThread:2940751 [wandb_init.py:init():798] finishing previous run: j0yzze8k
2025-04-13 05:41:52,867 WARNING MainThread:2940751 [wandb_init.py:init():1534] [no run ID] interrupted
Traceback (most recent call last):
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1530, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 799, in init
    wandb.run.finish()
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 483, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 425, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2182, in finish
    return self._finish(exit_code)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2204, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2431, in _atexit_cleanup
    self._on_finish()
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2690, in _on_finish
    wait_with_progress(
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 24, in wait_with_progress
    return wait_all_with_progress(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 87, in wait_all_with_progress
    return asyncio_compat.run(progress_loop_with_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/lib/asyncio_compat.py", line 30, in run
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 451, in result
    self._condition.wait(timeout)
  File "/usr/lib/python3.11/threading.py", line 327, in wait
    waiter.acquire()
KeyboardInterrupt
2025-04-13 05:41:54,609 INFO    MsgRouterThr:2940751 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 11 handles.
